spring:
  jpa:
    show-sql: false
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQLDialect
    database: mysql
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect:org.hibernate.dialect.MySQLDialect
  properties:
    hibernate:
      default_schema: personkit
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    password: "Yishui@36"
    #    url: jdbc:mysql://47.111.112.103:3306/personkit?useUnicode=true&characterEncoding=UTF-8&pinGlobalTxToPhysicalConnection=true&useSSL=false&createDatabaseIfNotExist=true
    password: "123456ss"
    url: jdbc:mysql://10.168.1.115:3306/personkit?useUnicode=true&characterEncoding=UTF-8&pinGlobalTxToPhysicalConnection=true&useSSL=false&createDatabaseIfNotExist=true
    username: root
    #https://cloud.tencent.com/developer/article/1707872
    hikari:
      # 连接池最大连接数，默认是 10
      maximum-pool-size: 60
      # 链接超时时间，默认 30000(30 秒)
      connection-timeout: 60000
      # 空闲连接存活最大时间，默认 600000(10 分钟)
      idle-timeout: 60000
      # 连接将被测试活动的最大时间量
      validation-timeout: 3000
      # 此属性控制池中连接的最长生命周期，值 0 表示无限生命周期，默认 1800000(30 分钟)
      max-lifetime: 60000
      # 连接到数据库时等待的最长时间(秒)
      login-timeout: 5
      # 池中维护的最小空闲连接数
      minimum-idle: 10
